### ISSUE TITLE
Intermittent tests

### ISSUE THREAD

**Issue by hazeltonbw** [hazeltonbw/ecommerce-backend#13] opened 2023-03-19 05:38 UTC
Jest tests sometimes pass, sometimes fail. The response from the back-end sometimes returns undefined, when we are expecting a user object. Need to investigate this further with a debugger.

**Comment by mdwiltfong** [comment] 2023-03-19 15:05
Hey @hazeltonbw ! Looking at this, I think the problem is that the tests aren't passing in a session in the various tests. If you assign this issue to me as well as your #12 branch I should be able to help out!

**Comment by hazeltonbw** [comment] 2023-03-19 22:44
> Hey @hazeltonbw ! Looking at this, I think the problem is that the tests aren't passing in a session in the various tests. If you assign this issue to me as well as your #12 branch I should be able to help out!

I have you assigned with the branch linked to the issue! Thank you for taking a look at this for me.

**Comment by mdwiltfong** [comment] 2023-03-20 02:13
Okay, so i haven't gotten a chance to troubleshoot the real issue yet because it looks like there is an issue with deleting records that reference foreign keys. 


I've provided an example of an error message below that appears when trying to delete a record. You can replicate a similar error by trying to delete a user from the User table. 

In my notes, this error message means that SQL is protecting the database by making sure a record that is referenced in other tables isn't deleted by mistake. You can override this through the phrase `CASCADE ON DELETE`. Here's an example: 

` CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) 
   ON DELETE CASCADE` 
   
 I think we can add this phrase [here](https://github.com/hazeltonbw/ecommerce-backend/blob/fd1bfc2d68392aa4b76339fc3f57d5b7826509d2/db/setupDatabase.js#L122) although i'm not too familiar with `MATCH SIMPLE`. I will try this to see if that resolves the issue. 
 
 What do you think @hazeltonbw ?

```
 console.log
    ERROR SEEDING ONE OR MORE TABLES:  error: insert or update on table "cart_has_products" violates foreign key constraint "cart_has_products_product_id_fkey"
        at Parser.parseErrorMessage (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/parser.ts:369:69)
        at Parser.handlePacket (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/parser.ts:188:21)
        at Parser.parse (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/parser.ts:103:30)
        at Socket.<anonymous> (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/index.ts:7:48)
        at Socket.emit (node:events:520:28)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Socket.Readable.push (node:internal/streams/readable:228:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
      length: 302,
      severity: 'ERROR',
      code: '23503',
      detail: 'Key (product_id)=(1) is not present in table "products".',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'cart_has_products',
      column: undefined,
      dataType: undefined,
      constraint: 'cart_has_products_product_id_fkey',
      file: 'ri_triggers.c',
      line: '2463',
      routine: 'ri_ReportViolation'
    }
```

**Comment by hazeltonbw** [comment] 2023-03-20 20:16
> Okay, so i haven't gotten a chance to troubleshoot the real issue yet because it looks like there is an issue with deleting records that reference foreign keys.
> 
> I've provided an example of an error message below that appears when trying to delete a record. You can replicate a similar error by trying to delete a user from the User table.
> 
> In my notes, this error message means that SQL is protecting the database by making sure a record that is referenced in other tables isn't deleted by mistake. You can override this through the phrase `CASCADE ON DELETE`. Here's an example:
> 
> ` CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE`
> 
> I think we can add this phrase [here](https://github.com/hazeltonbw/ecommerce-backend/blob/fd1bfc2d68392aa4b76339fc3f57d5b7826509d2/db/setupDatabase.js#L122) although i'm not too familiar with `MATCH SIMPLE`. I will try this to see if that resolves the issue.
> 
> What do you think @hazeltonbw ?
> 
> ```
>  console.log
>     ERROR SEEDING ONE OR MORE TABLES:  error: insert or update on table "cart_has_products" violates foreign key constraint "cart_has_products_product_id_fkey"
>         at Parser.parseErrorMessage (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/parser.ts:369:69)
>         at Parser.handlePacket (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/parser.ts:188:21)
>         at Parser.parse (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/parser.ts:103:30)
>         at Socket.<anonymous> (/home/mdwiltfong/codecademy/ecommerce-backend/node_modules/pg-protocol/src/index.ts:7:48)
>         at Socket.emit (node:events:520:28)
>         at addChunk (node:internal/streams/readable:315:12)
>         at readableAddChunk (node:internal/streams/readable:289:9)
>         at Socket.Readable.push (node:internal/streams/readable:228:10)
>         at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
>       length: 302,
>       severity: 'ERROR',
>       code: '23503',
>       detail: 'Key (product_id)=(1) is not present in table "products".',
>       hint: undefined,
>       position: undefined,
>       internalPosition: undefined,
>       internalQuery: undefined,
>       where: undefined,
>       schema: 'public',
>       table: 'cart_has_products',
>       column: undefined,
>       dataType: undefined,
>       constraint: 'cart_has_products_product_id_fkey',
>       file: 'ri_triggers.c',
>       line: '2463',
>       routine: 'ri_ReportViolation'
>     }
> ```

I've fixed the problem, but I think we'll run into another issue once we start adding real users or products to the database. What do you think about separating databases (production/test)? This way we can insert however many in the tests, clear it when we're done, and can always be sure what's in the test database.

**Comment by mdwiltfong** [comment] 2023-03-21 00:43
@hazeltonbw , yes! That's a good idea. Although that might be worth doing after the tests can be run successfully. I would recommend creating an issue so you can remember to do that. It might also be worth creating a `clearProdDB` So that when you demo the project, you can clear the production site, and make sure your demos go smoothly.

**Comment by mdwiltfong** [comment] 2023-03-21 12:13
Hey @hazeltonbw ,

This might have been silly to do, but I moved `clearDatabase` from [here](https://github.com/hazeltonbw/ecommerce-backend/blob/09e023455d56c08fa687d92cb21478113b80919b/db/seedDatabase.js#L150) to a [separate file](https://github.com/mdwiltfong/ecommerce-backend/blob/mdwiltfong/issue13/tests/_testCommon.js). I did this because when exporting the function into `auth.test.js` I noticed that it was triggering the IIFE that you have at the bottom of `seedDatabase`. That IIFE is there contributors to run `npm run seedDatabase` , right? I noticed that `clearDatabase` wasn't being used in `seedDatabase` so I thought it would be okay to move it. Not sure if that regresses some other functionality.


By moving this function into a separate file, you can now clear the database before and after running your tests. Let me know if that regresses some other aspect of the app.

**Closed as completed** 2023-06-05 06:34 UTC
